language: scala
dist: trusty
script: ./tools/travis-script.sh
after_success: ./tools/travis-deploy.sh
branches:
  only:
    - master
    - 1.12.x
    - 1.13.x
    - 1.14.x
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC2
jdk:
  - oraclejdk8
  - openjdk11
env:
  global:
    - secure: PwIb1un8vuuyoidnjHaKO81FD49n5ZTVEnf6hVKkMRe3hipr+WGWv19m92yE/n34ROFo1BM9DmfYxaexlE0pI2o/a5MV1i3kNSwUk+Yt8uU6F4+nyQKROQUe76UtAtXmsYgLqXaWSW0+EVidMyhSktkXXxiU5wCGLdKkPu3Vj9w=
    - secure: KeZRD91oE4UzwhSJfjllkwNXnerDGQJSIOuRLVtbLCq0JJnAfj6B7fvI2KyZqQwuhYrUyYOSbSLd6BAi75bBYMb3D1yNdyPA5gHDg5aj96ALojrOuU60+/dOQ0Rg6Pf2UiTlFAXzz1mud8+Q3svaeKX4JDVxj329T3ReBspjyBY=
  matrix:
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=4 DEPLOY=false
    - PLATFORM=jvm SBT_PARALLEL=false WORKERS=4 DEPLOY=false
    - PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
    - PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true SCALAJS_VERSION=1.0.0-M7
sudo: false

matrix:
  include:
    - scala: 2.11.12
      before_script:
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      sudo: required
      addons:
        apt:
          update: true # https://github.com/rickynils/scalacheck/issues/412
      env: PLATFORM=native SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
    - env: EXAMPLES
      script:
      - cd examples
      - for d in */ ; do cd "$d" && sbt test:compile && cd ../ ; done
  exclude:
    - scala: 2.10.7
      env: PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true SCALAJS_VERSION=1.0.0-M7
    - jdk: openjdk11
      scala: 2.10.7
    - jdk: openjdk11
      scala: 2.11.12
    - scala: 2.13.0-RC2
      env: PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true SCALAJS_VERSION=0.6.27
